######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 16 10:59:17 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = subdirs

# Directories
SUBDIRS += Debug.pro
