######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 16 11:21:39 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = subdirs

# Directories
SUBDIRS += Debug.pro
