#ifndef CAMERA_HARDWARE_H
#define CAMERA_HARDWARE_H

#define VIEWPORT_HEIGHT_PIX 60
#define VIEWPORT_WIDTH_PIX 80
#define VIEWPORT_FOV_DEGREES_VERTICAL 37
#define VIEWPORT_FOV_DEGREES_HORIZONTAL 51
#define PI 3.14159265358979

#endif