//
// Created by paul on 01/06/15.
//

#ifndef OBSTACLE_AVOIDANCE_HORIZONMEDIALRESCALER_H
#define OBSTACLE_AVOIDANCE_HORIZONMEDIALRESCALER_H


class HorizonMedianRescaler {

};


#endif //OBSTACLE_AVOIDANCE_HORIZONMEDIALRESCALER_H
