######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 16 11:58:12 2015
######################################################################

CONFIG += qtestlib
TEMPLATE = subdirs

# Directories
SUBDIRS += Play.pro
