//
// Created by paul on 01/06/15.
//

#ifndef OBSTACLE_AVOIDANCE_HORIZONMEDIALRESCALERTEST_H
#define OBSTACLE_AVOIDANCE_HORIZONMEDIALRESCALERTEST_H


class HorizonMedialRescalerTest {

};


#endif //OBSTACLE_AVOIDANCE_HORIZONMEDIALRESCALERTEST_H
