//
// Created by Aditi Chakravarthi on 15-08-09.
//

#ifndef OBSTACLE_AVOIDANCE_SIMPLEDANGERZONEENCODERTEST_H
#define OBSTACLE_AVOIDANCE_SIMPLEDANGERZONEENCODERTEST_H


class SimpleDangerZoneEncoderTest {

};


#endif //OBSTACLE_AVOIDANCE_SIMPLEDANGERZONEENCODERTEST_H
